name: Publish to NuGet

on:
  push:
    tags:
      - v*

jobs:
  call-publish-workflow:
    uses: Lombiq/GitHub-Actions/.github/workflows/publish-nuget.yml@dev
    with:
      # Don't generate any symbol package because we're not including the Lombiq.Analyzers.dll in the NuGet package
      # itself, either. See Invoke-BeforePack.ps1 for details.
      dotnet-pack-include-symbols: "false"
    secrets:
      API_KEY: ${{ secrets.DEFAULT_NUGET_PUBLISH_API_KEY }}
